### model
model_name_or_path: /mnt/publiccache/huggingface/Mistral-7B-Instruct-v0.2
model_type: mistral


### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 16
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: apibank_training_chat
template: mistral_tool
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
only_train_on_last_round: True

### output
output_dir: /mnt/publiccache/yphao/model/apibank/apibank_mistral_instruct_lora
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

# ### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### other 
report_to: none
